name: Query Toronto Bike Share

permissions:
  contents: write
  
on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:       # Also allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Run data collection and cleaning script
        run: python BikeShareTO/query_bikeshare.py

      - name: Commit and push data to data-logs branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
          git checkout -B data-logs
      
          git add BikeShareTO/station_status/station_status_log.csv BikeShareTO/station_status/station_status_recent.csv
      
          git commit -m "Update bike share data $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
      
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:data-logs
